using Domain.Documents.Entities;
using Domain.Enums;
using Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Persistence.Seeding;

public static partial class SeedingExtensions
{
	public static ModelBuilder SeedDocumentData(this ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Document>().HasData(
			new Document
			{
				Id = -1, Code = "A-93489", Title = "Buying some stuff", IsActive = true,
				Created = new DateTime(2023, 01, 02), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 02),
				LastModifiedBy = "Jane Doe"
			},
			// the following data is mostly generated by ChatGPT with some help from me
			new Document
			{
				Id = -2, Code = "B-93847", Title = "Planning a trip", IsActive = true,
				Created = new DateTime(2023, 01, 07), CreatedBy = "Jane Doe", LastModified = new DateTime(2023, 01, 08),
				LastModifiedBy = "John Doe"
			},
			new Document
			{
				Id = -3, Code = "C-94857", Title = "Buying a car", IsActive = false,
				Created = new DateTime(2023, 01, 11), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 11),
				LastModifiedBy = "Jane Doe"
			},
			new Document
			{
				Id = -4, Code = "D-85738", Title = "Traveling to Hawaii", IsActive = true,
				Created = new DateTime(2023, 01, 18), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 19),
				LastModifiedBy = "Jane Doe"
			},
			new Document
			{
				Id = -5, Code = "E-11223", Title = "Organizing a trip", IsActive = true,
				Created = new DateTime(2023, 01, 18), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 18),
				LastModifiedBy = "Jane Doe"
			},
			new Document
			{
				Id = -6, Code = "F-98546", Title = "Planning a vacation", IsActive = true,
				Created = new DateTime(2023, 01, 22), CreatedBy = "Jane Doe", LastModified = new DateTime(2023, 01, 22),
				LastModifiedBy = "John Doe"
			},

			new Document
			{
				Id = -7, Code = "E-34569", Title = "Organizing a party", IsActive = true,
				Created = new DateTime(2023, 01, 21), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 21),
				LastModifiedBy = "Jane Doe"
			},
			new Document
			{
				Id = -8, Code = "F-65487", Title = "Planning a vacation",  IsActive = false,
				Created = new DateTime(2023, 01, 25), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 25),
				LastModifiedBy = "Jane Doe"
			},
			new Document
			{
				Id = -9, Code = "E-94748", Title = "Planning a trip to the moon", IsActive = true,
				Created = new DateTime(2023, 01, 19), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 19),
				LastModifiedBy = "Jane Doe"
			},
			new Document
			{
				Id = -10, Code = "F-73848", Title = "Exploring new galaxies", IsActive = false,
				Created = new DateTime(2023, 01, 22), CreatedBy = "John Doe", LastModified = new DateTime(2023, 01, 22),
				LastModifiedBy = "Jane Doe"
			}
		);

		modelBuilder.Entity<DocumentDetail>().HasData(
			new()
			{
				Id = -11,
				DocumentId = -1,
				Text = "Getting offers",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 03),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 06),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -12,
				DocumentId = -2,
				Text = "Talk to stakeholders",
				Priority = PriorityLevel.Medium,
				Solved = false,
				Created = new DateTime(2023, 01, 05),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 05),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -21,
				DocumentId = -2,
				Text = "Book flight tickets",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 09),
				CreatedBy = "Tester Y",
				LastModified = new DateTime(2023, 01, 11),
				LastModifiedBy = "Tester Y",
			},
			new()
			{
				Id = -22,
				DocumentId = -2,
				Text = "Find accommodations",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 10),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 12),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -31,
				DocumentId = -3,
				Text = "Compare prices",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 12),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 13),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -32,
				DocumentId = -3,
				Text = "Arrange test drive",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 13),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 13),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -41,
				DocumentId = -4,
				Text = "Book flights",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 20),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 21),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -42,
				DocumentId = -4,
				Text = "Book accommodation",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 21),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 21),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -51,
				DocumentId = -5,
				Text = "Book flights",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 19),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 20),
				LastModifiedBy = "Tester X"
			},
			new()
			{
				Id = -52,
				DocumentId = -5,
				Text = "Find accommodation",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 20),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 20),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -61,
				DocumentId = -6,
				Text = "Research destinations",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 23),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 24),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -62,
				DocumentId = -6,
				Text = "Book flights",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 24),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 24),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -71,
				DocumentId = -7,
				Text = "Find a venue",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 22),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 23),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -72,
				DocumentId = -7,
				Text = "Prepare guest list",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 23),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 23),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -81,
				DocumentId = -8,
				Text = "Research destinations",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 26),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 27),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -82,
				DocumentId = -8,
				Text = "Book flights",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 27),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 27),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -91,
				DocumentId = -9,
				Text = "Book a flight",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 20),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 20),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -92,
				DocumentId = -9,
				Text = "Find a good hotel",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 21),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 21),
				LastModifiedBy = "None"
			},
			new()
			{
				Id = -101,
				DocumentId = -10,
				Text = "Find a spaceship",
				Priority = PriorityLevel.High,
				Solved = false,
				Created = new DateTime(2023, 01, 23),
				CreatedBy = "Tester X",
				LastModified = new DateTime(2023, 01, 23),
				LastModifiedBy = "Tester X",
			},
			new()
			{
				Id = -102,
				DocumentId = -10,
				Text = "Gather supplies",
				Priority = PriorityLevel.Low,
				Solved = false,
				Created = new DateTime(2023, 01, 24),
				CreatedBy = "Me",
				LastModified = new DateTime(2023, 01, 24),
				LastModifiedBy = "None"
			}
		);

		return modelBuilder;
	}
}